#  设置服务名
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xyl?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: 1q2w3e4r!

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true

logging:
  level:
    org:
      example:
        weekly:
          export:
            mapper: debug
